### ISSUE TITLE
error: covariance is not positive-definite

### ISSUE THREAD

**Issue by lex-crater** [ldeecke/gmm-torch#31]
why would this happen?
`log_det[k] = 2 * torch.log(torch.diagonal(torch.linalg.cholesky(var[0,k]))).sum()
torch._C._LinAlgError: torch.linalg_cholesky: The factorization could not be completed because the input is not positive-definite (the leading minor of order 128 is not positive-definite).
`

**Comment by ldeecke** [comment]
Hi,

Can you provide a minimal example?

**Comment by breadli428** [comment]
The right parenthesis is placed in the wrong place.
Fix `return -.5 * (self.n_features * np.log(2. * pi) + log_p - log_det)` in `_estimate_log_prob`.

**Comment by ldeecke** [comment]
I've pushed a fix in b3a45cea3b6e1dd76bad4c09c9f0377e15f56e87. Thanks for helping me locate this @breadli428!

**Comment by linxiao-Shi** [comment]
I still have the same problem in new code, when I use it for images.

x_truth = cv2.imread(os.path.join(img_path, path))
x_truth = torch.tensor(x_truth, device=device)
……………………………………
patch = x_truth[sub_h:sub_h_end, sub_w:sub_w_end, :]
patch_h, patch_w, patch_c = patch.shape
patch = patch.flatten().reshape(patch_h*patch_w, patch_c)
gmm = gmm.GaussianMixture(n_components = 2, n_features = 3).cuda()
gmm.fit(patch)
cls = gmm.predict(patch.flatten().reshape(patch_h*patch_w,patch_c))
